
services:
  database:
    image: 'postgres'
    container_name: 'postgres-${APP_NAME}'
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net

  application:
    container_name: 'api-${APP_NAME}'
    restart: always
    build:
      context: .
      dockerfile: ./.docker/Dockerfile.${DOCKER_ENV}
    volumes:
      - ./api:/usr/src/app/
    ports:
      - ${APP_PORT}:8080
    networks:
      - app-net
    depends_on:
      - database
    env_file:
      - .env

networks:
  app-net:
    driver: bridge

volumes:
  postgres_data:
    driver: local
